const all = [
  "Pagglait",
  "The Girl on the Train",
  "Tribhanga - Tedhi Medhi Crazy",
  "Bombay Rose",
  "Indoo Ki Jawani",
  "Gunjan Saxena: The Kargil Girl",
  "Ginny Weds Sunny",
  "Madam Chief Minister",
  "Shimla Mirchi",
  "Class of '83",
  "Jai Mummy Di",
  "Door Ke Darshan",
  "Bulbbul",
  "Raat Akeli Hai",
  "Serious Men",
  "Mrs. Serial Killer",
  "AK vs AK",
  "Love Aaj Kal",
  "Little Singham: Kaal Ka Badla",
  "Choked: Paisa Bolta Hai",
  "Guilty",
  "Dolly Kitty Aur Woh Chamakte Sitare",
  "Maska",
  "Torbaaz",
  "Ghost Stories",
  "Chaman Bahaar",
  "Little Singham: Legend of Dugabakka",
  "Chippa",
  "Axone",
  "Kaali Khuhi",
  "Yeh Ballet",
  "Har Kisse Ke Hisse: Kaamyaab",
  "Cargo",
  "Ludo",
  "Fukrey Boyzzz: Space Mein Fukrapanti",
  "Malang",
  "What Are the Odds?",
  "Article 15",
  "Drive",
  "The Sky Is Pink",
  "Badla",
  "The Body",
  "Bypass Road",
  "Kabir Singh",
  "Luka Chuppi",
  "Made in China",
  "Ek Ladki Ko Dekha Toh Aisa Laga",
  "One Day: Justice Delivered",
  "Motichoor Chaknachoor",
  "Panipat - The Great Betrayal",
  "Romeo Akbar Walter",
  "Thackeray (Hindi)",
  "The Zoya Factor",
  "Game Over (Hindi Version)",
  "House Arrest",
  "Pranaam",
  "Bhangra Paa Le",
  "Chopsticks",
  "Chhota Bheem Kungfu Dhamaka",
  "Malaal",
  "Little Singham: Kaal Ki Tabaahi",
  "Little Singham in London",
  "Upstarts",
  "Eeb Allay Ooo!",
  "Little Singham: Mahabali",
  "Paharganj",
  "Music Teacher",
  "Little Singham Bandarpur Mein Hu Ha Hu",
  "Penalty",
  "Mere Pyare Prime Minister",
  "Saaho",
  "Rakkhosh",
  "Albert Pinto Ko Gussa Kyun Aata Hai?",
  "Andhadhun",
  "Is Love Enough? Sir",
  "Stree",
  "Parmanu: The Story of Pokhran",
  "Aiyaary",
  "Pad Man",
  "Baazaar",
  "Zero",
  "Sanju",
  "Love Per Square Foot",
  "Lust Stories",
  "Lupt",
  "Mard Ko Dard Nahi Hota",
  "Soorma",
  "Pihu",
  "Rajma Chawal",
  "Ascharyachakit!",
  "Beyond the Clouds",
  "Hope Aur Hum",
  "Jaoon Kahan Bata Ae Dil",
  "Soni",
  "Chhota Bheem Ka Romani Adventure",
  "Evening Shadows",
  "Bhavesh Joshi Superhero",
  "Samudri Lootere",
  "Garbage",
  "My Birthday Song",
  "Brij Mohan Amar Rahe",
  "Manto",
  "Dragonkala Ka Rahasya",
  "Kuchh Bheege Alfaaz",
  "Halkaa",
  "Super Bheem Bana Vajraveer",
  "Bheemayan",
  "Three and a Half",
  "Period. End of Sentence.",
  "Life of An Outcast",
  "Antariksha Ke Rakhwale",
  "Bombairiya",
  "Hamid",
  "Ladies First",
  "Zoo",
  "Baahubali 2: The Conclusion (Hindi Version)",
  "Naam Shabana",
  "Ittefaq",
  "Mubarakan",
  "Judwaa 2",
  "Half Girlfriend",
  "Raees",
  "Jagga Jasoos",
  "Bareilly Ki Barfi",
  "Secret Superstar",
  "Mom",
  "Toilet: Ek Prem Katha",
  "Baadshaho",
  "Jab Harry Met Sejal",
  "Qarib Qarib Singlle",
  "Kaabil",
  "Poster Boys",
  "The House Next Door",
  "Gurgaon",
  "Love and Shukla",
  "Lucknow Central",
  "B.A. Pass 2",
  "Rangoon",
  "Ajji",
  "Running Shaadi",
  "The Wishing Tree",
  "Candyflip",
  "Bhasmasur",
  "Baaghi",
  "Dangal",
  "Rocky Handsome",
  "Dear Zindagi",
  "Mohenjo Daro",
  "Kapoor & Sons",
  "Pink",
  "Fitoor",
  "TE3N",
  "Wazir",
  "Udta Punjab",
  "Raman Raghav 2.0",
  "The Legend of Michael Mishra",
  "Santa Banta Pvt Ltd",
  "Tu Hai Mera Sunday",
  "Budhia Singh: Born to Run",
  "Shortcut Safari",
  "Autohead",
  "Force 2",
  "The Violin Player",
  "Dear Dad",
  "Project Marathwada",
  "CRD",
  "Baahubali: The Beginning (Hindi Version)",
  "Drishyam",
  "Dilwale",
  "Gabbar Is Back",
  "Dil Dhadakne Do",
  "Tamasha",
  "Shaandaar",
  "ABCD 2",
  "Prem Ratan Dhan Payo",
  "Dharam Sankat Mein",
  "Pyaar Ka Punchnama 2",
  "Brothers",
  "Phantom",
  "Bangistan",
  "X: Past Is Present",
  "Hunterrr",
  "Haraamkhor",
  "Katti Batti",
  "Waiting",
  "Hawaizaada",
  "Time Out",
  "Zubaan",
  "Muzaffarnagar Baaqi Hai",
  "Happy New Year",
  "PK",
  "2 States",
  "Khoobsurat",
  "Humpty Sharma Ki Dulhania",
  "Raja Natwarlal",
  "Hasee Toh Phasee",
  "Queen",
  "Highway",
  "Haider",
  "Bobby Jasoos",
  "Mary Kom",
  "Mighty Raju Rio Calling",
  "Mumbai Delhi Mumbai",
  "Pizza",
  "Ungli",
  "Dedh Ishqiya",
  "Gollu aur Pappu",
  "One by Two",
  "Court",
  "Chal Bhaag",
  "Yeh Hai Bakrapur",
  "Boss",
  "Special 26",
  "Madras Café",
  "ABCD: Any Body Can Dance",
  "Race 2",
  "Gori Tere Pyaar Mein",
  "Chashme Baddoor",
  "Himmatwala",
  "Fukrey",
  "Kai Po Che!",
  "B.A. Pass",
  "Nasha",
  "Saheb Biwi Aur Gangster Returns",
  "Ghanchakkar",
  "Bombay Talkies",
  "Inkaar",
  "Satyagraha",
  "What the Fish",
  "Deewana Main Deewana",
  "Liar's Dice",
  "Ankhon Dekhi",
  "War Chhod Na Yaar",
  "Fireflies",
  "Oh My God",
  "Rowdy Rathore",
  "Joker",
  "Players",
  "Barfi!",
  "Talaash",
  "Kahaani",
  "Luv Shuv Tey Chicken Khurana",
  "Aiyyaa",
  "Ek Main Aur Ekk Tu",
  "Heroine",
  "Chhota Bheem and the Curse of Damyaan",
  "Blood Money",
  "Ferrari Ki Sawaari",
  "Tere Naal Love Ho Gaya",
  "Life Ki Toh Lag Gayi",
  "Bittoo Boss",
  "Fatso",
  "Mumbai Cha Raja",
  "Singham",
  "Zindagi Na Milegi Dobara",
  "Don 2",
  "Bodyguard",
  "Thank You",
  "Game",
  "Bbuddah Hoga Terra Baap",
  "No One Killed Jessica",
  "Chillar Party",
  "Arjun: The Warrior Prince",
  "Tanu Weds Manu",
  "7 Khoon Maaf",
  "Zokkomon",
  "Shaitan",
  "Michael",
  "My Friend Pinto",
  "I Hate Luv Storys",
  "I Am Kalam",
  "Paan Singh Tomar",
  "Action Replayy",
  "Raajneeti",
  "Tum Milo Toh Sahi",
  "Udaan",
  "We Are Family",
  "Chance Pe Dance",
  "Karthik Calling Karthik",
  "Do Dooni Chaar",
  "Break Ke Baad",
  "Guzaarish",
  "That Girl in Yellow Boots",
  "I Am",
  "Dhoondte Reh Jaoge",
  "Ajab Prem Ki Ghazab Kahani",
  "Wake Up Sid",
  "Billu",
  "Kurbaan",
  "Delhi 6",
  "3 Idiots",
  "What's Your Raashee?",
  "Ishqiya",
  "Well Done Abba",
  "Agyaat",
  "Dev.D",
  "Luck by Chance",
  "Aagey Se Right",
  "Do Paise Ki Dhoop Chaar Aane Ki Baarish",
  "Kisaan",
  "Main aurr Mrs. Khanna",
  "Kaminey",
  "Golmaal Returns",
  "Jodhaa Akbar",
  "Race",
  "Dostana",
  "Kismat Konnection",
  "Rock On!!",
  "Oye Lucky! Lucky Oye!",
  "Mumbai Meri Jaan",
  "Fashion",
  "Welcome to Sajjanpur",
  "Ugly Aur Pagli",
  "Contract",
  "Aamir",
  "Om Shanti Om",
  "Welcome",
  "Jab We Met",
  "Dhan Dhana Dhan Goal",
  "Guru",
  "Namastey London",
  "Manorama Six Feet Under",
  "Honeymoon Travels Pvt. Ltd.",
  "Life in a ... Metro",
  "Hattrick",
  "Chup Chup Ke",
  "Phir Hera Pheri",
  "Don",
  "Kabhi Alvida Naa Kehna",
  "Rang De Basanti",
  "Vivah",
  "Anthony Kaun Hai?",
  "Pyaar Ke Side Effects",
  "BluffMaster!",
  "Kaal",
  "Paheli",
  "Apaharan",
  "Shabd",
  "The Blue Umbrella",
  "Main, Meri Patni Aur Woh",
  "Ek Khiladi Ek Haseena",
  "Main Hoon Na",
  "Swades",
  "Lakshya",
  "Yuva",
  "Chameli",
  "Fida",
  "Black Friday",
  "Kal Ho Naa Ho",
  "Gangaajal",
  "Chalte Chalte",
  "Ishq Vishk",
  "Mumbai Matinee",
  "Hazaaron Khwaishein Aisi",
  "Jhankaar Beats",
  "Awara Paagal Deewana",
  "The Legend of Bhagat Singh",
  "Sur: The Melody of Life",
  "Kabhi Khushi Kabhie Gham",
  "Dil Chahta Hai",
  "Asoka",
  "One 2 Ka 4",
  "Phir Bhi Dil Hai Hindustani",
  "Fiza",
  "Hum Saath-Saath Hain",
  "Hello Brother",
  "Mann",
  "Kuch Kuch Hota Hai",
  "Duplicate",
  "Dil Se",
  "Soldier",
  "Qila",
  "Chaahat",
  "English Babu Desi Mem",
  "Ram Jaane",
  "Oh Darling Yeh Hai India",
  "Andaz Apna Apna",
  "Hum Aapke Hain Koun",
  "Kabhi Haan Kabhi Naa",
  "Yaar Gaddar",
  "Aashik Awara",
  "Gumrah",
  "Maya Memsaab",
  "Chamatkar",
  "Shikari",
  "Agneepath",
  "Dil",
  "Mujrim",
  "Aakhri Adaalat",
  "Muqaddar ka Faisla",
  "Jaal",
  "Pyar Ke Do Pal",
  "Duniya",
  "Sohni Mahiwal",
  "Ek Jaan Hain Hum",
  "Disco Dancer",
  "Dostana (1980)",
  "Alibaba Aur 40 Chor",
  "Bandie",
  "Salaakhen",
  "Manoranjan",
  "Khoon Khoon",
  "Elaan",
  "Lal Patthar",
  "Prince",
  "Amrapali",
  "Professor",
  "Singapore",
  "Ujala",
  "706",
  "Rukh",
  "The Silence",
  "Azhar",
  "Horror Story",
  "Beyond All Boundaries",
  "Dhobi Ghat (Mumbai Diaries)",
  "Peepli Live",
  "Jaane Tu... Ya Jaane Na",
  "Taare Zameen Par",
  "Socha Na Tha",
  "Lagaan",
  "Tuesdays & Fridays",
  "Ajeeb Daastaans",
  "Roohi",
  "Rudra: Secret of the Black Moon",
  "Ram Prasad Ki Tehrvi",
  "Motu Patlu in the Game of Zones",
  "Rudra: The Rise of King Pharaoh",
  "Motu Patlu the Superheroes – Super Villains from Mars",
  "Motu Patlu VS Robo Kids",
  "Shiva: Journey to Plunotaria",
  "Motu Patlu in the City of Gold",
  "Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers",
  "Motu Patlu Dino Invasion",
  "Shiva VS Autobots",
  "Motu Patlu in Hong Kong: Kung Fu Kings 3",
  "Motu Patlu in Dragon's World",
  "Motu Patlu in Octupus World",
  "Shiva: The Secret World Of Vedas City",
  "Motu Patlu: Khazaane Ki Race",
  "Motu Patlu: Kung Fu Kings",
  "Motu Patlu: Deep Sea Adventure",
  "Motu Patlu: Mission Moon",
  "Motu Patlu in Wonderland",
  "Keymon and Nani in Space Adventure"
]