const movies = [
  "Tribhanga - Tedhi Medhi Crazy",
  "Shimla Mirchi",
  "Ginny Weds Sunny",
  "Raat Akeli Hai",
  "AK vs AK",
  "Gunjan Saxena: The Kargil Girl",
  "Serious Men",
  "Jai Mummy Di",
  "Class of '83",
  "Door Ke Darshan",
  "Mrs. Serial Killer",
  "Bulbbul",
  "Choked: Paisa Bolta Hai",
  "Love Aaj Kal",
  "Dolly Kitty Aur Woh Chamakte Sitare",
  "Torbaaz",
  "Maska",
  "Chaman Bahaar",
  "Guilty",
  "Yeh Ballet",
  "Chippa",
  "Cargo",
  "Ghost Stories",
  "Kaali Khuhi",
  "Little Singham: Kaal Ka Badla",
  "Axone",
  "Har Kisse Ke Hisse: Kaamyaab",
  "What Are the Odds?",
  "Little Singham: Legend of Dugabakka",
  "Malang",
  "Ludo",
  "Fukrey Boyzzz: Space Mein Fukrapanti",
  "Made in China",
  "Chopsticks",
  "Motichoor Chaknachoor",
  "Badla",
  "Drive",
  "Luka Chuppi",
  "Kabir Singh",
  "The Body",
  "The Sky Is Pink",
  "One Day: Justice Delivered",
  "Bhangra Paa Le",
  "The Zoya Factor",
  "Panipat - The Great Betrayal",
  "Bypass Road",
  "Article 15",
  "Pranaam",
  "Malaal",
  "Ek Ladki Ko Dekha Toh Aisa Laga",
  "Romeo Akbar Walter",
  "Thackeray (Hindi)",
  "House Arrest",
  "Game Over (Hindi Version)",
  "706",
  "Eeb Allay Ooo!",
  "Upstarts",
  "Penalty",
  "Chhota Bheem Kungfu Dhamaka",
  "Paharganj",
  "Little Singham: Mahabali",
  "Music Teacher",
  "Mere Pyare Prime Minister",
  "Little Singham: Kaal Ki Tabaahi",
  "Little Singham in London",
  "Saaho",
  "Little Singham Bandarpur Mein Hu Ha Hu",
  "Albert Pinto Ko Gussa Kyun Aata Hai?",
  "Rakkhosh",
  "Is Love Enough? Sir",
  "Parmanu: The Story of Pokhran",
  "Stree",
  "Aiyaary",
  "Zero",
  "Baazaar",
  "Sanju",
  "Rajma Chawal",
  "Pihu",
  "Andhadhun",
  "Love Per Square Foot",
  "Pad Man",
  "Soorma",
  "Mard Ko Dard Nahi Hota",
  "Beyond the Clouds",
  "Lupt",
  "Lust Stories",
  "Brij Mohan Amar Rahe",
  "Bhavesh Joshi Superhero",
  "Kuchh Bheege Alfaaz",
  "Ascharyachakit!",
  "Jaoon Kahan Bata Ae Dil",
  "Hope Aur Hum",
  "Soni",
  "Garbage",
  "Halkaa",
  "Bombairiya",
  "Bheemayan",
  "Manto",
  "Ladies First",
  "My Birthday Song",
  "Evening Shadows",
  "Hamid",
  "Chhota Bheem Ka Romani Adventure",
  "Three and a Half",
  "Super Bheem Bana Vajraveer",
  "Samudri Lootere",
  "Antariksha Ke Rakhwale",
  "Life of An Outcast",
  "Zoo",
  "Dragonkala Ka Rahasya",
  "Period. End of Sentence.",
  "Judwaa 2",
  "Toilet: Ek Prem Katha",
  "Baahubali 2: The Conclusion (Hindi Version)",
  "Ittefaq",
  "Secret Superstar",
  "Mubarakan",
  "Raees",
  "Naam Shabana",
  "Mom",
  "Jab Harry Met Sejal",
  "Half Girlfriend",
  "Bareilly Ki Barfi",
  "Jagga Jasoos",
  "Kaabil",
  "Qarib Qarib Singlle",
  "Love and Shukla",
  "Gurgaon",
  "Baadshaho",
  "Ajji",
  "Lucknow Central",
  "Rukh",
  "The Silence",
  "Rangoon",
  "Poster Boys",
  "The House Next Door",
  "B.A. Pass 2",
  "Running Shaadi",
  "The Wishing Tree",
  "Candyflip",
  "Bhasmasur",
  "Baaghi",
  "Dear Zindagi",
  "Dangal",
  "Mohenjo Daro",
  "TE3N",
  "Rocky Handsome",
  "Kapoor & Sons",
  "Pink",
  "Fitoor",
  "Santa Banta Pvt Ltd",
  "Raman Raghav 2.0",
  "Udta Punjab",
  "Budhia Singh: Born to Run",
  "Azhar",
  "Tu Hai Mera Sunday",
  "The Legend of Michael Mishra",
  "The Violin Player",
  "Shortcut Safari",
  "Dear Dad",
  "Autohead",
  "Project Marathwada",
  "CRD",
  "Force 2",
  "Dil Dhadakne Do",
  "Baahubali: The Beginning (Hindi Version)",
  "Gabbar Is Back",
  "Drishyam",
  "Dharam Sankat Mein",
  "Tamasha",
  "Dilwale",
  "Phantom",
  "Prem Ratan Dhan Payo",
  "Brothers",
  "Shaandaar",
  "Pyaar Ka Punchnama 2",
  "Guilty",
  "ABCD 2",
  "Bangistan",
  "Hunterrr",
  "X: Past Is Present",
  "Haraamkhor",
  "Zubaan",
  "Katti Batti",
  "Hawaizaada",
  "Waiting",
  "Time Out",
  "Muzaffarnagar Baaqi Hai",
  "Happy New Year",
  "PK",
  "2 States",
  "Khoobsurat",
  "Hasee Toh Phasee",
  "Humpty Sharma Ki Dulhania",
  "Raja Natwarlal",
  "Queen",
  "Bobby Jasoos",
  "Haider",
  "Mary Kom",
  "Mumbai Delhi Mumbai",
  "Highway",
  "Mighty Raju Rio Calling",
  "Pizza",
  "Gollu aur Pappu",
  "Court",
  "Chal Bhaag",
  "Dedh Ishqiya",
  "Yeh Hai Bakrapur",
  "One by Two",
  "Ungli",
  "Special 26",
  "Boss",
  "Race 2",
  "Gori Tere Pyaar Mein",
  "Chashme Baddoor",
  "Kai Po Che!",
  "Madras Café",
  "Fukrey",
  "ABCD: Any Body Can Dance",
  "Nasha",
  "Himmatwala",
  "B.A. Pass",
  "Horror Story",
  "Deewana Main Deewana",
  "Ankhon Dekhi",
  "Inkaar",
  "Saheb Biwi Aur Gangster Returns",
  "Satyagraha",
  "Ghanchakkar",
  "Bombay Talkies",
  "Liar's Dice",
  "What the Fish",
  "War Chhod Na Yaar",
  "Beyond All Boundaries",
  "Fireflies",
  "Rowdy Rathore",
  "Oh My God",
  "Players",
  "Joker",
  "Talaash",
  "Kahaani",
  "Barfi!",
  "Ek Main Aur Ekk Tu",
  "Aiyyaa",
  "Blood Money",
  "Heroine",
  "Luv Shuv Tey Chicken Khurana",
  "Chhota Bheem and the Curse of Damyaan",
  "Life Ki Toh Lag Gayi",
  "Bittoo Boss",
  "Mumbai Cha Raja",
  "Fatso",
  "Tere Naal Love Ho Gaya",
  "Zindagi Na Milegi Dobara",
  "Singham",
  "Don 2",
  "Thank You",
  "Bodyguard",
  "Game",
  "Tanu Weds Manu",
  "Chillar Party",
  "No One Killed Jessica",
  "Bbuddah Hoga Terra Baap",
  "Zokkomon",
  "Arjun: The Warrior Prince",
  "7 Khoon Maaf",
  "Shaitan",
  "Michael",
  "My Friend Pinto",
  "I Am Kalam",
  "We Are Family",
  "I Hate Luv Storys",
  "Action Replayy",
  "Raajneeti",
  "Paan Singh Tomar",
  "Udaan",
  "Dhobi Ghat (Mumbai Diaries)",
  "Chance Pe Dance",
  "Guzaarish",
  "Do Dooni Chaar",
  "Tum Milo Toh Sahi",
  "Break Ke Baad",
  "Karthik Calling Karthik",
  "Peepli Live",
  "That Girl in Yellow Boots",
  "I Am",
  "Dhoondte Reh Jaoge",
  "Ajab Prem Ki Ghazab Kahani",
  "Wake Up Sid",
  "Billu",
  "Main aurr Mrs. Khanna",
  "What's Your Raashee?",
  "Kurbaan",
  "Luck by Chance",
  "Dev.D",
  "Delhi 6",
  "Kisaan",
  "Aagey Se Right",
  "Kaminey",
  "Well Done Abba",
  "Do Paise Ki Dhoop Chaar Aane Ki Baarish",
  "Ishqiya",
  "Agyaat",
  "Jodhaa Akbar",
  "Dostana",
  "Race",
  "Golmaal Returns",
  "Oye Lucky! Lucky Oye!",
  "Jaane Tu... Ya Jaane Na",
  "Kismat Konnection",
  "Rock On!!",
  "Mumbai Meri Jaan",
  "Welcome to Sajjanpur",
  "Fashion",
  "Contract",
  "Aamir",
  "Ugly Aur Pagli",
  "Om Shanti Om",
  "Taare Zameen Par",
  "Welcome",
  "Jab We Met",
  "Namastey London",
  "Guru",
  "Dhan Dhana Dhan Goal",
  "Hattrick",
  "Manorama Six Feet Under",
  "Honeymoon Travels Pvt. Ltd.",
  "Life in a ... Metro",
  "Phir Hera Pheri",
  "Vivah",
  "Chup Chup Ke",
  "Don",
  "Kabhi Alvida Naa Kehna",
  "Rang De Basanti",
  "Anthony Kaun Hai?",
  "Pyaar Ke Side Effects",
  "BluffMaster!",
  "Paheli",
  "Apaharan",
  "Kaal",
  "Socha Na Tha",
  "Main, Meri Patni Aur Woh",
  "The Blue Umbrella",
  "Shabd",
  "Ek Khiladi Ek Haseena",
  "Main Hoon Na",
  "Swades",
  "Lakshya",
  "Yuva",
  "Fida",
  "Chameli",
  "Black Friday",
  "Kal Ho Naa Ho",
  "Gangaajal",
  "Chalte Chalte",
  "Ishq Vishk",
  "Jhankaar Beats",
  "Mumbai Matinee",
  "Hazaaron Khwaishein Aisi",
  "Awara Paagal Deewana",
  "The Legend of Bhagat Singh",
  "Sur: The Melody of Life",
  "Kabhi Khushi Kabhie Gham",
  "Lagaan",
  "Dil Chahta Hai",
  "One 2 Ka 4",
  "Asoka",
  "Phir Bhi Dil Hai Hindustani",
  "Fiza",
  "Hum Saath-Saath Hain",
  "Mann",
  "Hello Brother",
  "Kuch Kuch Hota Hai",
  "Duplicate",
  "Soldier",
  "Dil Se",
  "Qila",
  "English Babu Desi Mem",
  "Chaahat",
  "Ram Jaane",
  "Oh Darling Yeh Hai India",
  "Hum Aapke Hain Koun",
  "Andaz Apna Apna",
  "Kabhi Haan Kabhi Naa",
  "Yaar Gaddar",
  "Gumrah",
  "Aashik Awara",
  "Maya Memsaab",
  "Chamatkar",
  "Shikari",
  "Agneepath",
  "Dil",
  "Mujrim",
  "Aakhri Adaalat",
  "Muqaddar ka Faisla",
  "Jaal",
  "Pyar Ke Do Pal",
  "Duniya",
  "Sohni Mahiwal",
  "Ek Jaan Hain Hum",
  "Disco Dancer",
  "Dostana (1980)",
  "Alibaba Aur 40 Chor",
  "Bandie",
  "Salaakhen",
  "Manoranjan",
  "Khoon Khoon",
  "Elaan",
  "Lal Patthar",
  "Prince",
  "Amrapali",
  "Professor",
  "Singapore",
  "Ujala"
]