const movies = [
  "Sardar Ka Grandson",
  "Ajeeb Daastaans",
  "Pagglait",
  "The Girl on the Train",
  "Tribhanga - Tedhi Medhi Crazy",
  "Tuesdays & Fridays",
  "99 Songs",
  "Little Singham Future mein Satakli",
  "Bombay Rose",
  "Ahaan",
  "Milestone",
  "Roohi",
  "Ginny Weds Sunny",
  "Malang",
  "Gunjan Saxena: The Kargil Girl",
  "Indoo Ki Jawani",
  "Jai Mummy Di",
  "Madam Chief Minister",
  "Raat Akeli Hai",
  "AK vs AK",
  "Love Aaj Kal",
  "Door Ke Darshan",
  "Mrs. Serial Killer",
  "Shimla Mirchi",
  "Class of '83",
  "Serious Men",
  "Bulbbul",
  "Dolly Kitty Aur Woh Chamakte Sitare",
  "Torbaaz",
  "Ghost Stories",
  "Chaman Bahaar",
  "Time to Dance",
  "Guilty",
  "Little Singham: Kaal Ka Badla",
  "Kaali Khuhi",
  "Choked: Paisa Bolta Hai",
  "Maska",
  "Little Singham: Legend of Dugabakka",
  "Rudra: Secret of the Black Moon",
  "Axone",
  "Har Kisse Ke Hisse: Kaamyaab",
  "Yeh Ballet",
  "Cargo",
  "Chippa",
  "Ludo",
  "Fukrey Boyzzz: Space Mein Fukrapanti",
  "What Are the Odds?",
  "Saaho",
  "Kabir Singh",
  "Bypass Road",
  "Drive",
  "Article 15",
  "Luka Chuppi",
  "Made in China",
  "Romeo Akbar Walter",
  "Ram Prasad Ki Tehrvi",
  "The Body",
  "Badla",
  "Motichoor Chaknachoor",
  "One Day: Justice Delivered",
  "The Sky Is Pink",
  "The Zoya Factor",
  "Ek Ladki Ko Dekha Toh Aisa Laga",
  "Panipat - The Great Betrayal",
  "Chopsticks",
  "Thackeray (Hindi)",
  "Pranaam",
  "House Arrest",
  "Bhangra Paa Le",
  "Malaal",
  "Chhota Bheem Kungfu Dhamaka",
  "Game Over (Hindi Version)",
  "Little Singham: Mahabali",
  "Penalty",
  "Motu Patlu in the Game of Zones",
  "Upstarts",
  "Little Singham: Kaal Ki Tabaahi",
  "Rudra: The Rise of King Pharaoh",
  "Motu Patlu the Superheroes – Super Villains from Mars",
  "Little Singham Bandarpur Mein Hu Ha Hu",
  "Paharganj",
  "Motu Patlu VS Robo Kids",
  "Eeb Allay Ooo!",
  "Music Teacher",
  "Shiva: Journey to Plunotaria",
  "Mere Pyare Prime Minister",
  "Rakkhosh",
  "Albert Pinto Ko Gussa Kyun Aata Hai?",
  "Aiyaary",
  "Stree",
  "Pad Man",
  "Love Per Square Foot",
  "Parmanu: The Story of Pokhran",
  "Andhadhun",
  "Baazaar",
  "Sanju",
  "Zero",
  "Is Love Enough? Sir",
  "Soorma",
  "Lust Stories",
  "Mard Ko Dard Nahi Hota",
  "Pihu",
  "Rajma Chawal",
  "Bhavesh Joshi Superhero",
  "Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers",
  "Ascharyachakit!",
  "Kuchh Bheege Alfaaz",
  "Motu Patlu Dino Invasion",
  "Jaoon Kahan Bata Ae Dil",
  "Garbage",
  "My Birthday Song",
  "Manto",
  "Soni",
  "Hope Aur Hum",
  "Beyond the Clouds",
  "Brij Mohan Amar Rahe",
  "Motu Patlu in the City of Gold",
  "Halkaa",
  "Tottaa Pataaka Item Maal",
  "Shiva VS Autobots",
  "Three and a Half",
  "Bombairiya",
  "Evening Shadows",
  "Ladies First",
  "Period. End of Sentence.",
  "Hamid",
  "Zoo",
  "Life of An Outcast",
  "Naam Shabana",
  "Baahubali 2: The Conclusion (Hindi Version)",
  "Judwaa 2",
  "Mubarakan",
  "Ittefaq",
  "Raees",
  "Half Girlfriend",
  "Secret Superstar",
  "Bareilly Ki Barfi",
  "Mom",
  "Toilet: Ek Prem Katha",
  "Jab Harry Met Sejal",
  "Jagga Jasoos",
  "Kaabil",
  "Qarib Qarib Singlle",
  "Poster Boys",
  "Baadshaho",
  "The House Next Door",
  "Love and Shukla",
  "Lucknow Central",
  "Motu Patlu in Hong Kong: Kung Fu Kings 3",
  "B.A. Pass 2",
  "Ajji",
  "Running Shaadi",
  "Motu Patlu in Dragon's World",
  "Motu Patlu in Octupus World",
  "Rangoon",
  "Shiva: The Secret World Of Vedas City",
  "The Wishing Tree",
  "Bhasmasur",
  "Candyflip",
  "Baaghi",
  "Rocky Handsome",
  "Dangal",
  "Dear Zindagi",
  "Wazir",
  "Kapoor & Sons",
  "Mohenjo Daro",
  "Udta Punjab",
  "Tu Hai Mera Sunday",
  "TE3N",
  "Pink",
  "Fitoor",
  "Santa Banta Pvt Ltd",
  "Raman Raghav 2.0",
  "Budhia Singh: Born to Run",
  "The Legend of Michael Mishra",
  "Shortcut Safari",
  "Force 2",
  "The Violin Player",
  "Project Marathwada",
  "Autohead",
  "Gabbar Is Back",
  "Dil Dhadakne Do",
  "Drishyam",
  "Baahubali: The Beginning (Hindi Version)",
  "Dilwale",
  "Dharam Sankat Mein",
  "ABCD 2",
  "Brothers",
  "Shaandaar",
  "Prem Ratan Dhan Payo",
  "Tamasha",
  "Pyaar Ka Punchnama 2",
  "Phantom",
  "Guilty",
  "Hunterrr",
  "Bangistan",
  "X: Past Is Present",
  "Katti Batti",
  "Haraamkhor",
  "Hawaizaada",
  "Time Out",
  "Muzaffarnagar Baaqi Hai",
  "Happy New Year",
  "PK",
  "Ungli",
  "Humpty Sharma Ki Dulhania",
  "2 States",
  "Hasee Toh Phasee",
  "Khoobsurat",
  "Raja Natwarlal",
  "Queen",
  "Haider",
  "Mumbai Delhi Mumbai",
  "Gollu aur Pappu",
  "Mary Kom",
  "Highway",
  "Mighty Raju Rio Calling",
  "Pizza",
  "Bobby Jasoos",
  "Dedh Ishqiya",
  "Motu Patlu: Deep Sea Adventure",
  "Court",
  "Chal Bhaag",
  "Yeh Hai Bakrapur",
  "One by Two",
  "Special 26",
  "Race 2",
  "Boss",
  "Madras Café",
  "Fukrey",
  "Himmatwala",
  "ABCD: Any Body Can Dance",
  "Kai Po Che!",
  "Gori Tere Pyaar Mein",
  "Chashme Baddoor",
  "Satyagraha",
  "Nasha",
  "Motu Patlu: Mission Moon",
  "Inkaar",
  "Saheb Biwi Aur Gangster Returns",
  "Ghanchakkar",
  "Motu Patlu in Wonderland",
  "Keymon and Nani in Space Adventure",
  "Bombay Talkies",
  "Ankhon Dekhi",
  "What the Fish",
  "Deewana Main Deewana",
  "Liar's Dice",
  "Oh My God",
  "Players",
  "Rowdy Rathore",
  "Joker",
  "Kahaani",
  "Barfi!",
  "Talaash",
  "Ek Main Aur Ekk Tu",
  "Heroine",
  "Aiyyaa",
  "Blood Money",
  "Chhota Bheem and the Curse of Damyaan",
  "Luv Shuv Tey Chicken Khurana",
  "Ferrari Ki Sawaari",
  "Fatso",
  "Tere Naal Love Ho Gaya",
  "Life Ki Toh Lag Gayi",
  "Mumbai Cha Raja",
  "Thank You",
  "Singham",
  "Zindagi Na Milegi Dobara",
  "Don 2",
  "Bodyguard",
  "Chillar Party",
  "Tanu Weds Manu",
  "Game",
  "Bbuddah Hoga Terra Baap",
  "No One Killed Jessica",
  "Arjun: The Warrior Prince",
  "Zokkomon",
  "7 Khoon Maaf",
  "Shaitan",
  "Michael",
  "My Friend Pinto",
  "I Hate Luv Storys",
  "Action Replayy",
  "Break Ke Baad",
  "We Are Family",
  "Paan Singh Tomar",
  "Udaan",
  "Raajneeti",
  "I Am Kalam",
  "Tum Milo Toh Sahi",
  "Do Dooni Chaar",
  "Chance Pe Dance",
  "Karthik Calling Karthik",
  "Guzaarish",
  "Dhobi Ghat (Mumbai Diaries)",
  "That Girl in Yellow Boots",
  "Peepli Live",
  "3 Idiots",
  "Dhoondte Reh Jaoge",
  "Ajab Prem Ki Ghazab Kahani",
  "Billu",
  "Wake Up Sid",
  "Main aurr Mrs. Khanna",
  "What's Your Raashee?",
  "Kurbaan",
  "Kaminey",
  "Dev.D",
  "Delhi 6",
  "Agyaat",
  "Luck by Chance",
  "Kisaan",
  "Well Done Abba",
  "Aagey Se Right",
  "Do Paise Ki Dhoop Chaar Aane Ki Baarish",
  "Ishqiya",
  "Golmaal Returns",
  "Dostana",
  "Race",
  "Jodhaa Akbar",
  "Jaane Tu... Ya Jaane Na",
  "Kismat Konnection",
  "Oye Lucky! Lucky Oye!",
  "Rock On!!",
  "Mumbai Meri Jaan",
  "Fashion",
  "Welcome to Sajjanpur",
  "Ugly Aur Pagli",
  "Aamir",
  "Jab We Met",
  "Om Shanti Om",
  "Taare Zameen Par",
  "Namastey London",
  "Guru",
  "Dhan Dhana Dhan Goal",
  "Hattrick",
  "Life in a ... Metro",
  "Honeymoon Travels Pvt. Ltd.",
  "Manorama Six Feet Under",
  "Welcome",
  "Chup Chup Ke",
  "Phir Hera Pheri",
  "Don",
  "Kabhi Alvida Naa Kehna",
  "Vivah",
  "Rang De Basanti",
  "Anthony Kaun Hai?",
  "Taxi No. 9211",
  "Pyaar Ke Side Effects",
  "BluffMaster!",
  "Paheli",
  "Main, Meri Patni Aur Woh",
  "Kaal",
  "Apaharan",
  "Ek Khiladi Ek Haseena",
  "The Blue Umbrella",
  "Shabd",
  "Main Hoon Na",
  "Swades",
  "Lakshya",
  "Fida",
  "Yuva",
  "Chameli",
  "Black Friday",
  "Kal Ho Naa Ho",
  "Chalte Chalte",
  "Gangaajal",
  "Ishq Vishk",
  "Jhankaar Beats",
  "Mumbai Matinee",
  "Hazaaron Khwaishein Aisi",
  "Awara Paagal Deewana",
  "The Legend of Bhagat Singh",
  "Sur: The Melody of Life",
  "Kabhi Khushi Kabhie Gham",
  "Lagaan",
  "Dil Chahta Hai",
  "Asoka",
  "One 2 Ka 4",
  "Phir Bhi Dil Hai Hindustani",
  "Fiza",
  "Hum Saath-Saath Hain",
  "Hello Brother",
  "Mann",
  "Kuch Kuch Hota Hai",
  "Duplicate",
  "Soldier",
  "Dil Se",
  "Qila",
  "English Babu Desi Mem",
  "Chaahat",
  "Ram Jaane",
  "Oh Darling Yeh Hai India",
  "Andaz Apna Apna",
  "Hum Aapke Hain Koun",
  "Kabhi Haan Kabhi Naa",
  "Yaar Gaddar",
  "Aashik Awara",
  "Gumrah",
  "Maya Memsaab",
  "Chamatkar",
  "Shikari",
  "Dil",
  "Agneepath",
  "Mujrim",
  "Aakhri Adaalat",
  "Muqaddar ka Faisla",
  "Pyar Ke Do Pal",
  "Jaal",
  "Sohni Mahiwal",
  "Duniya",
  "Ek Jaan Hain Hum",
  "Disco Dancer",
  "Dostana (1980)",
  "Alibaba Aur 40 Chor",
  "Bandie",
  "Salaakhen",
  "Manoranjan",
  "Khoon Khoon",
  "Lal Patthar",
  "Elaan",
  "Prince",
  "Amrapali",
  "Professor",
  "Singapore",
  "Ujala"
]