const allRemoved = [
  "Little Singham in London",
  "Lupt",
  "Chhota Bheem Ka Romani Adventure",
  "Samudri Lootere",
  "Dragonkala Ka Rahasya",
  "Super Bheem Bana Vajraveer",
  "Bheemayan",
  "Antariksha Ke Rakhwale",
  "Gurgaon",
  "Dear Dad",
  "CRD",
  "Waiting",
  "Zubaan",
  "B.A. Pass",
  "War Chhod Na Yaar",
  "Fireflies",
  "Bittoo Boss",
  "I Am",
  "Contract",
  "706",
  "Rukh",
  "The Silence",
  "Azhar",
  "Horror Story",
  "Beyond All Boundaries",
  "Socha Na Tha",
  "Motu Patlu: Khazaane Ki Race",
  "Motu Patlu: Kung Fu Kings"
]